name: Core checks

on:
  workflow_call:

env:
  HUSKY: 0

jobs:
  format_lint:
    name: Check formatting and linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/node-pnpm-action
        with:
          pnpm-install: true

      - run: |
          pnpm biome ci

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/node-pnpm-action
        with:
          pnpm-install: true

      - run: |
          pnpm test
