name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: false

env:
  HUSKY: 0

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml

  release:
    needs: [checks]
    name: Publish a release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: ./.github/actions/node-pnpm-action
        with:
          pnpm-install: true

      - run: |
          pnpm exec release-it
